2019-04-14 21:18:46,864 ERROR 5994 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at processImmediate (timers.js:637:19)
From previous event:
    at ConnectionManager._connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/lifecycle.js:248:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 5994
hostname: wuxinghengdeMacBook-Pro.local

2019-04-14 21:32:20,817 ERROR 11785 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at processImmediate (timers.js:637:19)
From previous event:
    at ConnectionManager._connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/lifecycle.js:248:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 11785
hostname: wuxinghengdeMacBook-Pro.local

2019-04-14 21:33:59,565 ERROR 12547 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at processImmediate (timers.js:637:19)
From previous event:
    at ConnectionManager._connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/lifecycle.js:248:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 12547
hostname: wuxinghengdeMacBook-Pro.local

2019-04-14 21:35:48,548 ERROR 13298 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at processImmediate (timers.js:637:19)
From previous event:
    at ConnectionManager._connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/lifecycle.js:248:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 13298
hostname: wuxinghengdeMacBook-Pro.local

2019-04-14 21:51:02,571 ERROR 19810 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at processImmediate (timers.js:637:19)
From previous event:
    at ConnectionManager._connect (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/egg-core/lib/lifecycle.js:248:13)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 19810
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 00:22:42,617 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 5214229ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 00:28:27,831 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 305116ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 01:55:51,529 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 5203678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 08:53:56,076 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 25084474ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 08:57:44,580 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 88528ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-15 09:04:33,544 ERROR 41384 nodejs.ClusterClientNoResponseError: client no response in 288934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 41384
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:56:01,303 ERROR 38667 [-/::1/-/693ms POST /api/login] nodejs.Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/jsonwebtoken/sign.js:107:20)
    at createToken (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:7:19)
    at User.login (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:57:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

pid: 38667
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:57:10,327 ERROR 39024 [-/::1/-/6330ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":3},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":6308,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 39024
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:57:12,488 ERROR 39024 [-/::1/-/7110ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 2
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7108,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 39024
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:57:14,689 ERROR 39024 [-/::1/-/7148ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 3
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7147,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061HD0fx1Mpoqh0gRPgx1f5hfx1HD0fq&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 39024
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:57:16,277 ERROR 39024 [-/::1/-/6490ms POST /api/login] nodejs.Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/jsonwebtoken/sign.js:107:20)
    at createToken (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:7:19)
    at User.login (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:57:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

pid: 39024
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:58:09,023 ERROR 39479 [-/::1/-/7130ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0018JSeA07IZqe1Kn3fA01v0fA08JSeo&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0018JSeA07IZqe1Kn3fA01v0fA08JSeo&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7109,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0018JSeA07IZqe1Kn3fA01v0fA08JSeo&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 39479
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:58:14,978 ERROR 39479 [-/::1/-/6440ms POST /api/login] nodejs.Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/jsonwebtoken/sign.js:107:20)
    at createToken (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:7:19)
    at User.login (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:57:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

pid: 39479
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:59:42,493 ERROR 40182 [-/::1/-/7194ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":3},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7172,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40182
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:59:46,275 ERROR 40182 [-/::1/-/7176ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 2
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7174,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40182
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:59:47,541 ERROR 40182 [-/::1/-/7138ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 3
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7137,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40182
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 15:59:48,657 ERROR 40182 [-/::1/-/7157ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 4
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7156,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0611elSt1BHbZd0VwRSt1sDgSt11elSd&grant_type=authorization_code"],"timing":null,"remoteAddress":"183.232.103.145","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40182
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 16:00:42,174 ERROR 40607 [-/::1/-/7149ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":3},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7127,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code"],"timing":null,"remoteAddress":"120.198.199.239","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40607
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 16:00:46,497 ERROR 40607 [-/::1/-/7107ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"api.weixin.qq.com:443::::::::::::::::::":2},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 2
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7105,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=071Xbpx31LqxGQ1Hrpy31Smbx31Xbpxp&grant_type=authorization_code"],"timing":null,"remoteAddress":"120.198.199.239","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40607
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 16:02:06,356 ERROR 40607 [-/::1/-/7108ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061ElesE1q4jp708gHqE14GbsE1Eles0&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":8,"createSocketErrorCount":0,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":5,"requestCount":5,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 8
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061ElesE1q4jp708gHqE14GbsE1Eles0&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7106,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=061ElesE1q4jp708gHqE14GbsE1Eles0&grant_type=authorization_code"],"timing":null,"remoteAddress":"120.198.199.239","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 40607
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 16:03:53,374 ERROR 41805 [-/::1/-/7178ms POST /api/login] nodejs.ResponseTimeoutError: Response timeout for 5000ms, GET https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0614UBgO0Dnqi42fRAhO0W0jgO04UBgL&grant_type=authorization_code -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/urllib/lib/urllib.js:869:15)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ResponseTimeoutError"
requestId: 1
data: undefined
path: "/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0614UBgO0Dnqi42fRAhO0W0jgO04UBgL&grant_type=authorization_code"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7153,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/sns/jscode2session?appid=wx5e6189f24363171b&secret=23f4e01eea5fa660ecbd802e55e1b91f&js_code=0614UBgO0Dnqi42fRAhO0W0jgO04UBgL&grant_type=authorization_code"],"timing":null,"remoteAddress":"120.198.199.239","remotePort":443,"socketHandledRequests":1,"socketHandledResponses":0}
pid: 41805
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 19:07:46,299 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 549540ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 19:17:47,814 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 561488ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 19:31:47,476 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 637989ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 19:34:33,403 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 65890ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 19:44:54,310 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 393110ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 20:20:53,303 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 2138986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 20:39:40,773 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 1087444ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 21:04:00,750 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 1076932ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 21:09:28,661 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 307899ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 21:47:10,614 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 2137051ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-20 22:24:09,050 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 2198424ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 04:52:55,662 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 23286592ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 06:41:12,245 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 6456567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 06:57:17,104 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 944850ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 07:05:07,052 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 429934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 07:45:57,637 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 2410569ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 10:47:30,559 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 10872913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 11:30:53,729 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 682956ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 11:43:58,440 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 664679ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 12:32:19,097 ERROR 77424 nodejs.ClusterClientNoResponseError: client no response in 1660380ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 77424
hostname: wuxinghengdeMacBook-Pro.local

2019-04-21 12:38:39,092 ERROR 34874 [-/::1/-/482ms POST /api/login] nodejs.Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/node_modules/jsonwebtoken/sign.js:107:20)
    at createToken (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:7:19)
    at User.login (/Users/wuxh/Documents/coder/github/example/taro/kaikeba/sequelize/app/service/api.js:57:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

pid: 34874
hostname: wuxinghengdeMacBook-Pro.local

